# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3504efff7b4f967541d1a6f1e9220652515a204f2b8efc90794236847fd46c7c7dea6e4896bdf7abb63cabcf13a218dd1e973eb78dfae163a67d01fc978eb2c9

test:
  secret_key_base: b56a204171bada81b42472b46020e9a2163659549efb6b0f515fbf3c4cabc975073de3b88d7de52d0a99bebc3c9484fe7c2858b6b292a546de7c7ac9815623de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
